# Exported from Render on 2024-05-27T05:46:10Z
services:
- type: web
  name: meetupapi
  runtime: python
  repo: https://github.com/kabilanr/meetupapi
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn apiproject.wsgi
version: "1"